sudo: required
services:
  - docker

before_install: # production docker will not allow us to run any tests
  - docker build -t gaotheta/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run gaotheta/react-test npm test

after_success:
  - docker build -t gaotheta/multi-frontend ./frontend
  - docker build -t gaotheta/multi-nginx ./nginx
  - docker build -t gaotheta/multi-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gaotheta/multi-frontend
  - docker push gaotheta/multi-nginx
  - docker push gaotheta/multi-server
